/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MTA_MTA_PB_H_INCLUDED
#define PB_MTA_MTA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _mta_CorrelationDelta {
    uint32_t delta;
} mta_CorrelationDelta;

typedef PB_BYTES_ARRAY_T(256) mta_BobSetup_public_key_t;
typedef struct _mta_BobSetup {
    bool success;
    pb_callback_t ot_messages;
    mta_BobSetup_public_key_t public_key;
    uint32_t num_ot_instances;
} mta_BobSetup;

typedef struct _mta_AliceMessages {
    uint32_t masked_share;
    pb_callback_t ot_choices;
    pb_callback_t encrypted_shares;
} mta_AliceMessages;

typedef PB_BYTES_ARRAY_T(256) mta_BobMessages_encrypted_result_t;
typedef struct _mta_BobMessages {
    bool success;
    pb_callback_t ot_responses;
    mta_BobMessages_encrypted_result_t encrypted_result;
    uint32_t correlation_check;
} mta_BobMessages;

typedef struct _mta_MTAResult {
    bool success;
    uint32_t additive_share;
    char error_message[128];
} mta_MTAResult;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define mta_CorrelationDelta_init_default        {0}
#define mta_BobSetup_init_default                {0, {{NULL}, NULL}, {0, {0}}, 0}
#define mta_AliceMessages_init_default           {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define mta_BobMessages_init_default             {0, {{NULL}, NULL}, {0, {0}}, 0}
#define mta_MTAResult_init_default               {0, 0, ""}
#define mta_CorrelationDelta_init_zero           {0}
#define mta_BobSetup_init_zero                   {0, {{NULL}, NULL}, {0, {0}}, 0}
#define mta_AliceMessages_init_zero              {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define mta_BobMessages_init_zero                {0, {{NULL}, NULL}, {0, {0}}, 0}
#define mta_MTAResult_init_zero                  {0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define mta_CorrelationDelta_delta_tag           1
#define mta_BobSetup_success_tag                 1
#define mta_BobSetup_ot_messages_tag             2
#define mta_BobSetup_public_key_tag              3
#define mta_BobSetup_num_ot_instances_tag        4
#define mta_AliceMessages_masked_share_tag       1
#define mta_AliceMessages_ot_choices_tag         2
#define mta_AliceMessages_encrypted_shares_tag   3
#define mta_BobMessages_success_tag              1
#define mta_BobMessages_ot_responses_tag         2
#define mta_BobMessages_encrypted_result_tag     3
#define mta_BobMessages_correlation_check_tag    4
#define mta_MTAResult_success_tag                1
#define mta_MTAResult_additive_share_tag         2
#define mta_MTAResult_error_message_tag          3

/* Struct field encoding specification for nanopb */
#define mta_CorrelationDelta_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   delta,             1)
#define mta_CorrelationDelta_CALLBACK NULL
#define mta_CorrelationDelta_DEFAULT NULL

#define mta_BobSetup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, REPEATED, BYTES,    ot_messages,       2) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        3) \
X(a, STATIC,   SINGULAR, UINT32,   num_ot_instances,   4)
#define mta_BobSetup_CALLBACK pb_default_field_callback
#define mta_BobSetup_DEFAULT NULL

#define mta_AliceMessages_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   masked_share,      1) \
X(a, CALLBACK, REPEATED, BOOL,     ot_choices,        2) \
X(a, CALLBACK, REPEATED, BYTES,    encrypted_shares,   3)
#define mta_AliceMessages_CALLBACK pb_default_field_callback
#define mta_AliceMessages_DEFAULT NULL

#define mta_BobMessages_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, REPEATED, BYTES,    ot_responses,      2) \
X(a, STATIC,   SINGULAR, BYTES,    encrypted_result,   3) \
X(a, STATIC,   SINGULAR, UINT32,   correlation_check,   4)
#define mta_BobMessages_CALLBACK pb_default_field_callback
#define mta_BobMessages_DEFAULT NULL

#define mta_MTAResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, UINT32,   additive_share,    2) \
X(a, STATIC,   SINGULAR, STRING,   error_message,     3)
#define mta_MTAResult_CALLBACK NULL
#define mta_MTAResult_DEFAULT NULL

extern const pb_msgdesc_t mta_CorrelationDelta_msg;
extern const pb_msgdesc_t mta_BobSetup_msg;
extern const pb_msgdesc_t mta_AliceMessages_msg;
extern const pb_msgdesc_t mta_BobMessages_msg;
extern const pb_msgdesc_t mta_MTAResult_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define mta_CorrelationDelta_fields &mta_CorrelationDelta_msg
#define mta_BobSetup_fields &mta_BobSetup_msg
#define mta_AliceMessages_fields &mta_AliceMessages_msg
#define mta_BobMessages_fields &mta_BobMessages_msg
#define mta_MTAResult_fields &mta_MTAResult_msg

/* Maximum encoded size of messages (where known) */
/* mta_BobSetup_size depends on runtime parameters */
/* mta_AliceMessages_size depends on runtime parameters */
/* mta_BobMessages_size depends on runtime parameters */
#define MTA_MTA_PB_H_MAX_SIZE                    mta_MTAResult_size
#define mta_CorrelationDelta_size                6
#define mta_MTAResult_size                       138

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
