/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "mta.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mta_CorrelationDelta, mta_CorrelationDelta, AUTO)


PB_BIND(mta_BobSetup, mta_BobSetup, 2)


PB_BIND(mta_AliceMessages, mta_AliceMessages, AUTO)


PB_BIND(mta_BobMessages, mta_BobMessages, 2)


PB_BIND(mta_MTAResult, mta_MTAResult, AUTO)



